DROP PROCEDURE IF EXISTS scan_creature_smart_scripts;
DELIMITER //
CREATE PROCEDURE scan_creature_smart_scripts(IN entryInput int)
BEGIN
	set @inputActionLength := (select length(entryInput) + 2);
	set @name = (select name from creature_template where entry = entryInput);
	select @name
		, id
		, case when source_type = 0 then Concat(source_type,' Creature')
			when source_type = 1 then concat(source_type,' Game Object')
			when source_type = 9 then Concat(source_type, ' Action',right(entryorguid,2))
		end as Source_Type,
		link,
		event_phase_mask,
		event_chance,
		event_flags,
		case when event_type = 0 then concat(event_type, ' SMART_EVENT_UPDATE_IC')
			when event_type = 1 then concat(event_type, ' SMART_EVENT_UPDATE_OOC')
			when event_type = 2 then concat(event_type, ' SMART_EVENT_HEALTH_PCT')
			when event_type = 3 then concat(event_type, ' SMART_EVENT_MANA_PCT')
			when event_type = 4 then concat(event_type, ' SMART_EVENT_AGGRO')
			when event_type = 5 then concat(event_type, ' SMART_EVENT_KILL')
			when event_type = 6 then concat(event_type, ' SMART_EVENT_DEATH')
			when event_type = 7 then concat(event_type, ' SMART_EVENT_EVADE')
			when event_type = 8 then concat(event_type, ' SMART_EVENT_SPELLHIT')
			when event_type = 9 then concat(event_type, ' SMART_EVENT_RANGE')
			when event_type = 10 then concat(event_type, ' SMART_EVENT_OOC_LOS')
			when event_type = 11 then concat(event_type, ' SMART_EVENT_RESPAWN')
			when event_type = 12 then concat(event_type, ' SMART_EVENT_TARGET_HEALTH_PCT')
			when event_type = 13 then concat(event_type, ' SMART_EVENT_VICTIM_CASTING')
			when event_type = 14 then concat(event_type, ' SMART_EVENT_FRIENDLY_HEALTH')
			when event_type = 15 then concat(event_type, ' SMART_EVENT_FRIENDLY_IS_CC')
			when event_type = 16 then concat(event_type, ' SMART_EVENT_FRIENDLY_MISSING_BUFF')
			when event_type = 17 then concat(event_type, ' SMART_EVENT_SUMMONED_UNIT')
			when event_type = 18 then concat(event_type, ' SMART_EVENT_TARGET_MANA_PCT')
			when event_type = 19 then concat(event_type, ' SMART_EVENT_ACCEPTED_QUEST')
			when event_type = 20 then concat(event_type, ' SMART_EVENT_REWARD_QUEST')
			when event_type = 21 then concat(event_type, ' SMART_EVENT_REACHED_HOME')
			when event_type = 22 then concat(event_type, ' SMART_EVENT_RECEIVE_EMOTE')
			when event_type = 23 then concat(event_type, ' SMART_EVENT_HAS_AURA')
			when event_type = 24 then concat(event_type, ' SMART_EVENT_TARGET_BUFFED')
			when event_type = 25 then concat(event_type, ' SMART_EVENT_RESET')
			when event_type = 26 then concat(event_type, ' SMART_EVENT_IC_LOS')
			when event_type = 27 then concat(event_type, ' SMART_EVENT_PASSENGER_BOARDED')
			when event_type = 28 then concat(event_type, ' SMART_EVENT_PASSENGER_REMOVED')
			when event_type = 29 then concat(event_type, ' SMART_EVENT_CHARMED')
			when event_type = 30 then concat(event_type, ' SMART_EVENT_CHARMED_TARGET')
			when event_type = 31 then concat(event_type, ' SMART_EVENT_SPELLHIT_TARGET')
			when event_type = 32 then concat(event_type, ' SMART_EVENT_DAMAGED')
			when event_type = 33 then concat(event_type, ' SMART_EVENT_DAMAGED_TARGET')
			when event_type = 34 then concat(event_type, ' SMART_EVENT_MOVEMENTINFORM')
			when event_type = 35 then concat(event_type, ' SMART_EVENT_SUMMON_DESPAWNED')
			when event_type = 36 then concat(event_type, ' SMART_EVENT_CORPSE_REMOVED')
			when event_type = 37 then concat(event_type, ' SMART_EVENT_AI_INIT')
			when event_type = 38 then concat(event_type, ' SMART_EVENT_DATA_SET')
			when event_type = 39 then concat(event_type, ' SMART_EVENT_WAYPOINT_START')
			when event_type = 40 then concat(event_type, ' SMART_EVENT_WAYPOINT_REACHED')
			when event_type = 41 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_ADDPLAYER')
			when event_type = 42 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_ADDCREATURE')
			when event_type = 43 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_REMOVE_PLAYER')
			when event_type = 44 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_RELOCATE')
			when event_type = 45 then concat(event_type, ' X_SMART_EVENT_INSTANCE_PLAYER_ENTER')
			when event_type = 46 then concat(event_type, ' SMART_EVENT_AREATRIGGER_ONTRIGGER')
			when event_type = 47 then concat(event_type, ' X_SMART_EVENT_QUEST_ACCEPTED')
			when event_type = 48 then concat(event_type, ' X_SMART_EVENT_QUEST_OBJ_COMPLETION')
			when event_type = 49 then concat(event_type, ' X_SMART_EVENT_QUEST_COMPLETION')
			when event_type = 50 then concat(event_type, ' X_SMART_EVENT_QUEST_REWARDED')
			when event_type = 51 then concat(event_type, ' X_SMART_EVENT_QUEST_FAIL')
			when event_type = 52 then concat(event_type, ' SMART_EVENT_TEXT_OVER')
			when event_type = 53 then concat(event_type, ' SMART_EVENT_RECEIVE_HEAL')
			when event_type = 54 then concat(event_type, ' SMART_EVENT_JUST_SUMMONED')
			when event_type = 55 then concat(event_type, ' SMART_EVENT_WAYPOINT_PAUSED')
			when event_type = 56 then concat(event_type, ' SMART_EVENT_WAYPOINT_RESUMED')
			when event_type = 57 then concat(event_type, ' SMART_EVENT_WAYPOINT_STOPPED')
			when event_type = 58 then concat(event_type, ' SMART_EVENT_WAYPOINT_ENDED')
			when event_type = 59 then concat(event_type, ' SMART_EVENT_TIMED_EVENT_TRIGGERED')
			when event_type = 60 then concat(event_type, ' SMART_EVENT_UPDATE')
			when event_type = 61 then concat(event_type, ' SMART_EVENT_LINK')
			when event_type = 62 then concat(event_type, ' SMART_EVENT_GOSSIP_SELECT')
			when event_type = 63 then concat(event_type, ' SMART_EVENT_JUST_CREATED')
			when event_type = 64 then concat(event_type, ' SMART_EVENT_GOSSIP_HELLO')
			when event_type = 65 then concat(event_type, ' SMART_EVENT_FOLLOW_COMPLETED')
			when event_type = 66 then concat(event_type, ' SMART_EVENT_EVENT_PHASE_CHANGE')
			when event_type = 67 then concat(event_type, ' SMART_EVENT_IS_BEHIND_TARGET')
			when event_type = 68 then concat(event_type, ' SMART_EVENT_GAME_EVENT_START')
			when event_type = 69 then concat(event_type, ' SMART_EVENT_GAME_EVENT_END')
			when event_type = 70 then concat(event_type, ' SMART_EVENT_GO_LOOT_STATE_CHANGED')
			when event_type = 71 then concat(event_type, ' SMART_EVENT_GO_EVENT_INFORM')
			when event_type = 72 then concat(event_type, ' SMART_EVENT_ACTION_DONE')
			when event_type = 73 then concat(event_type, ' SMART_EVENT_ON_SPELLCLICK')
			when event_type = 74 then concat(event_type, ' SMART_EVENT_FRIENDLY_HEALTH_PCT')
			when event_type = 75 then concat(event_type, ' SMART_EVENT_DISTANCE_CREATURE')
			when event_type = 76 then concat(event_type, ' SMART_EVENT_DISTANCE_GAMEOBJECT')
			when event_type = 77 then concat(event_type, ' SMART_EVENT_COUNTER_SET')
			when event_type = 78 then concat(event_type, ' SMART_EVENT_SCENE_START')
			when event_type = 79 then concat(event_type, ' SMART_EVENT_SCENE_TRIGGER')
			when event_type = 80 then concat(event_type, ' SMART_EVENT_SCENE_CANCEL')
			when event_type = 81 then concat(event_type, ' SMART_EVENT_SCENE_COMPLETE')
			when event_type = 82 then concat(event_type, ' SMART_EVENT_SUMMONED_UNIT_DIES')
		end as Event_Type,
		event_param1,
		event_param2,
		event_param3,
		event_param4,
		event_param5,
		case when action_type = 0 then concat(action_type, ' SMART_ACTION_NONE')
			when action_type = 1 then concat(action_type, ' SMART_ACTION_TALK')
			when action_type = 2 then concat(action_type, ' SMART_ACTION_SET_FACTION')
			when action_type = 3 then concat(action_type, ' SMART_ACTION_MORPH_TO_ENTRY_OR_MODEL')
			when action_type = 4 then concat(action_type, ' SMART_ACTION_SOUND')
			when action_type = 5 then concat(action_type, ' SMART_ACTION_PLAY_EMOTE')
			when action_type = 6 then concat(action_type, ' SMART_ACTION_FAIL_QUEST')
			when action_type = 7 then concat(action_type, ' SMART_ACTION_OFFER_QUEST')
			when action_type = 8 then concat(action_type, ' SMART_ACTION_SET_REACT_STATE')
			when action_type = 9 then concat(action_type, ' SMART_ACTION_ACTIVATE_GOBJECT')
			when action_type = 10 then concat(action_type, ' SMART_ACTION_RANDOM_EMOTE')
			when action_type = 11 then concat(action_type, ' SMART_ACTION_CAST')
			when action_type = 12 then concat(action_type, ' SMART_ACTION_SUMMON_CREATURE')
			when action_type = 13 then concat(action_type, ' SMART_ACTION_THREAT_SINGLE_PCT')
			when action_type = 14 then concat(action_type, ' SMART_ACTION_THREAT_ALL_PCT')
			when action_type = 15 then concat(action_type, ' SMART_ACTION_CALL_AREAEXPLOREDOREVENTHAPPENS')
			when action_type = 16 then concat(action_type, ' SMART_ACTION_SET_INGAME_PHASE_ID')
			when action_type = 17 then concat(action_type, ' SMART_ACTION_SET_EMOTE_STATE')
			when action_type = 18 then concat(action_type, ' SMART_ACTION_SET_UNIT_FLAG')
			when action_type = 19 then concat(action_type, ' SMART_ACTION_REMOVE_UNIT_FLAG')
			when action_type = 20 then concat(action_type, ' SMART_ACTION_AUTO_ATTACK')
			when action_type = 21 then concat(action_type, ' SMART_ACTION_ALLOW_COMBAT_MOVEMENT')
			when action_type = 22 then concat(action_type, ' SMART_ACTION_SET_EVENT_PHASE')
			when action_type = 23 then concat(action_type, ' SMART_ACTION_INC_EVENT_PHASE')
			when action_type = 24 then concat(action_type, ' SMART_ACTION_EVADE')
			when action_type = 25 then concat(action_type, ' SMART_ACTION_FLEE_FOR_ASSIST')
			when action_type = 26 then concat(action_type, ' SMART_ACTION_CALL_GROUPEVENTHAPPENS')
			when action_type = 27 then concat(action_type, ' SMART_ACTION_COMBAT_STOP')
			when action_type = 28 then concat(action_type, ' SMART_ACTION_REMOVEAURASFROMSPELL')
			when action_type = 29 then concat(action_type, ' SMART_ACTION_FOLLOW')
			when action_type = 30 then concat(action_type, ' SMART_ACTION_RANDOM_PHASE')
			when action_type = 31 then concat(action_type, ' SMART_ACTION_RANDOM_PHASE_RANGE')
			when action_type = 32 then concat(action_type, ' SMART_ACTION_RESET_GOBJECT')
			when action_type = 33 then concat(action_type, ' SMART_ACTION_CALL_KILLEDMONSTER')
			when action_type = 34 then concat(action_type, ' SMART_ACTION_SET_INST_DATA')
			when action_type = 35 then concat(action_type, ' SMART_ACTION_SET_INST_DATA64')
			when action_type = 36 then concat(action_type, ' SMART_ACTION_UPDATE_TEMPLATE')
			when action_type = 37 then concat(action_type, ' SMART_ACTION_DIE')
			when action_type = 38 then concat(action_type, ' SMART_ACTION_SET_IN_COMBAT_WITH_ZONE')
			when action_type = 39 then concat(action_type, ' SMART_ACTION_CALL_FOR_HELP')
			when action_type = 40 then concat(action_type, ' SMART_ACTION_SET_SHEATH')
			when action_type = 41 then concat(action_type, ' SMART_ACTION_FORCE_DESPAWN')
			when action_type = 42 then concat(action_type, ' SMART_ACTION_SET_INVINCIBILITY_HP_LEVEL')
			when action_type = 43 then concat(action_type, ' SMART_ACTION_MOUNT_TO_ENTRY_OR_MODEL')
			when action_type = 44 then concat(action_type, ' SMART_ACTION_SET_INGAME_PHASE_GROUP (for 4.3.4 +)')
			when action_type = 45 then concat(action_type, ' SMART_ACTION_SET_DATA')
			when action_type = 46 then concat(action_type, ' SMART_ACTION_ATTACK_STOP')
			when action_type = 47 then concat(action_type, ' SMART_ACTION_SET_VISIBILITY')
			when action_type = 48 then concat(action_type, ' SMART_ACTION_SET_ACTIVE')
			when action_type = 49 then concat(action_type, ' SMART_ACTION_ATTACK_START')
			when action_type = 50 then concat(action_type, ' SMART_ACTION_SUMMON_GO')
			when action_type = 51 then concat(action_type, ' SMART_ACTION_KILL_UNIT')
			when action_type = 52 then concat(action_type, ' SMART_ACTION_ACTIVATE_TAXI')
			when action_type = 53 then concat(action_type, ' SMART_ACTION_WP_START')
			when action_type = 54 then concat(action_type, ' SMART_ACTION_WP_PAUSE')
			when action_type = 55 then concat(action_type, ' SMART_ACTION_WP_STOP')
			when action_type = 56 then concat(action_type, ' SMART_ACTION_ADD_ITEM')
			when action_type = 57 then concat(action_type, ' SMART_ACTION_REMOVE_ITEM')
			when action_type = 58 then concat(action_type, ' SMART_ACTION_INSTALL_AI_TEMPLATE')
			when action_type = 59 then concat(action_type, ' SMART_ACTION_SET_RUN')
			when action_type = 60 then concat(action_type, ' SMART_ACTION_SET_DISABLE_GRAVITY')
			when action_type = 61 then concat(action_type, ' SMART_ACTION_SET_SWIM')
			when action_type = 62 then concat(action_type, ' SMART_ACTION_TELEPORT')
			when action_type = 63 then concat(action_type, ' SMART_ACTION_SET_COUNTER')
			when action_type = 64 then concat(action_type, ' SMART_ACTION_STORE_TARGET_LIST')
			when action_type = 65 then concat(action_type, ' SMART_ACTION_WP_RESUME')
			when action_type = 66 then concat(action_type, ' SMART_ACTION_SET_ORIENTATION')
			when action_type = 67 then concat(action_type, ' SMART_ACTION_CREATE_TIMED_EVENT')
			when action_type = 68 then concat(action_type, ' SMART_ACTION_PLAYMOVIE')
			when action_type = 69 then concat(action_type, ' SMART_ACTION_MOVE_TO_POS')
			when action_type = 70 then concat(action_type, ' SMART_ACTION_ENABLE_TEMP_GOBJ')
			when action_type = 71 then concat(action_type, ' SMART_ACTION_EQUIP')
			when action_type = 72 then concat(action_type, ' SMART_ACTION_CLOSE_GOSSIP')
			when action_type = 73 then concat(action_type, ' SMART_ACTION_TRIGGER_TIMED_EVENT')
			when action_type = 74 then concat(action_type, ' SMART_ACTION_REMOVE_TIMED_EVENT')
			when action_type = 75 then concat(action_type, ' SMART_ACTION_ADD_AURA')
			when action_type = 76 then concat(action_type, ' SMART_ACTION_OVERRIDE_SCRIPT_BASE_OBJECT')
			when action_type = 77 then concat(action_type, ' SMART_ACTION_RESET_SCRIPT_BASE_OBJECT')
			when action_type = 78 then concat(action_type, ' SMART_ACTION_CALL_SCRIPT_RESET')
			when action_type = 79 then concat(action_type, ' SMART_ACTION_SET_RANGED_MOVEMENT')
			when action_type = 80 then concat(action_type, ' SMART_ACTION_CALL_TIMED_ACTIONLIST')
			when action_type = 81 then concat(action_type, ' SMART_ACTION_SET_NPC_FLAG')
			when action_type = 82 then concat(action_type, ' SMART_ACTION_ADD_NPC_FLAG')
			when action_type = 83 then concat(action_type, ' SMART_ACTION_REMOVE_NPC_FLAG')
			when action_type = 84 then concat(action_type, ' SMART_ACTION_SIMPLE_TALK')
			when action_type = 85 then concat(action_type, ' SMART_ACTION_SELF_CAST')
			when action_type = 86 then concat(action_type, ' SMART_ACTION_CROSS_CAST')
			when action_type = 87 then concat(action_type, ' SMART_ACTION_CALL_RANDOM_TIMED_ACTIONLIST')
			when action_type = 88 then concat(action_type, ' SMART_ACTION_CALL_RANDOM_RANGE_TIMED_ACTIONLIST')
			when action_type = 89 then concat(action_type, ' SMART_ACTION_RANDOM_MOVE')
			when action_type = 90 then concat(action_type, ' SMART_ACTION_SET_UNIT_FIELD_BYTES_1')
			when action_type = 91 then concat(action_type, ' SMART_ACTION_REMOVE_UNIT_FIELD_BYTES_1')
			when action_type = 92 then concat(action_type, ' SMART_ACTION_INTERRUPT_SPELL')
			when action_type = 93 then concat(action_type, ' SMART_ACTION_SEND_GO_CUSTOM_ANIM')
			when action_type = 94 then concat(action_type, ' SMART_ACTION_SET_DYNAMIC_FLAG')
			when action_type = 95 then concat(action_type, ' SMART_ACTION_ADD_DYNAMIC_FLAG')
			when action_type = 96 then concat(action_type, ' SMART_ACTION_REMOVE_DYNAMIC_FLAG')
			when action_type = 97 then concat(action_type, ' SMART_ACTION_JUMP_TO_POS')
			when action_type = 98 then concat(action_type, ' SMART_ACTION_SEND_GOSSIP_MENU')
			when action_type = 99 then concat(action_type, ' SMART_ACTION_GO_SET_LOOT_STATE')
			when action_type = 100 then concat(action_type, ' SMART_ACTION_SEND_TARGET_TO_TARGET')
			when action_type = 101 then concat(action_type, ' SMART_ACTION_SET_HOME_POS')
			when action_type = 102 then concat(action_type, ' SMART_ACTION_SET_HEALTH_REGEN')
			when action_type = 103 then concat(action_type, ' SMART_ACTION_SET_ROOT')
			when action_type = 104 then concat(action_type, ' SMART_ACTION_SET_GO_FLAG')
			when action_type = 105 then concat(action_type, ' SMART_ACTION_ADD_GO_FLAG')
			when action_type = 106 then concat(action_type, ' SMART_ACTION_REMOVE_GO_FLAG')
			when action_type = 107 then concat(action_type, ' SMART_ACTION_SUMMON_CREATURE_GROUP')
			when action_type = 108 then concat(action_type, ' SMART_ACTION_SET_POWER')
			when action_type = 109 then concat(action_type, ' SMART_ACTION_ADD_POWER')
			when action_type = 110 then concat(action_type, ' SMART_ACTION_REMOVE_POWER')
			when action_type = 111 then concat(action_type, ' SMART_ACTION_GAME_EVENT_STOP')
			when action_type = 112 then concat(action_type, ' SMART_ACTION_GAME_EVENT_START')
			when action_type = 113 then concat(action_type, ' SMART_ACTION_START_CLOSEST_WAYPOINT')
			when action_type = 114 then concat(action_type, ' SMART_ACTION_MOVE_OFFSET')
			when action_type = 115 then concat(action_type, ' SMART_ACTION_RANDOM_SOUND')
			when action_type = 116 then concat(action_type, ' SMART_ACTION_SET_CORPSE_DELAY')
			when action_type = 117 then concat(action_type, ' SMART_ACTION_DISABLE_EVADE')
			when action_type = 118 then concat(action_type, ' SMART_ACTION_GO_SET_GO_STATE')
			when action_type = 119 then concat(action_type, ' SMART_ACTION_SET_CAN_FLY')
			when action_type = 120 then concat(action_type, ' SMART_ACTION_REMOVE_AURAS_BY_TYPE')
			when action_type = 121 then concat(action_type, ' SMART_ACTION_SET_SIGHT_DIST')
			when action_type = 122 then concat(action_type, ' SMART_ACTION_FLEE')
			when action_type = 123 then concat(action_type, ' SMART_ACTION_ADD_THREAT')
			when action_type = 124 then concat(action_type, ' SMART_ACTION_LOAD_EQUIPMENT')
			when action_type = 125 then concat(action_type, ' SMART_ACTION_TRIGGER_RANDOM_TIMED_EVENT')
			when action_type = 126 then concat(action_type, ' SMART_ACTION_REMOVE_ALL_GAMEOBJECTS')
			when action_type = 127 then concat(action_type, ' SMART_ACTION_PAUSE_MOVEMENT')
			when action_type = 128 then concat(action_type, ' SMART_ACTION_PLAY_ANIMKIT')
			when action_type = 129 then concat(action_type, ' SMART_ACTION_SCENE_PLAY')
			when action_type = 130 then concat(action_type, ' SMART_ACTION_SCENE_CANCEL')
			when action_type = 131 then concat(action_type, ' SMART_ACTION_SPAWN_SPAWNGROUP')
			when action_type = 132 then concat(action_type, ' SMART_ACTION_DESPAWN_SPAWNGROUP')
			when action_type = 133 then concat(action_type, ' SMART_ACTION_RESPAWN_BY_SPAWNID')
			when action_type = 134 then concat(action_type, ' SMART_ACTION_INVOKER_CAST')
			when action_type = 135 then concat(action_type, ' SMART_ACTION_PLAY_CINEMATIC ')
			when action_type = 136 then concat(action_type, ' SMART_ACTION_SET_MOVEMENT_SPEED ')
			when action_type = 137 then concat(action_type, ' SMART_ACTION_PLAY_SPELL_VISUAL_KIT')
			when action_type = 138 then concat(action_type, ' SMART_ACTION_OVERRIDE_LIGHT')
			when action_type = 139 then concat(action_type, ' SMART_ACTION_OVERRIDE_WEATHER')
		end as Action_Type,
		action_param1,
		action_param2,
		action_param3,
		action_param4,
		action_param5,
		action_param6,
		case when target_type = 0 then concat(target_type, ' SMART_TARGET_NONE')
			when target_type = 1 then concat(target_type, ' SMART_TARGET_SELF')
			when target_type = 2 then concat(target_type, ' SMART_TARGET_VICTIM')
			when target_type = 3 then concat(target_type, ' SMART_TARGET_HOSTILE_SECOND_AGGRO')
			when target_type = 4 then concat(target_type, ' SMART_TARGET_HOSTILE_LAST_AGGRO')
			when target_type = 5 then concat(target_type, ' SMART_TARGET_HOSTILE_RANDOM')
			when target_type = 6 then concat(target_type, ' SMART_TARGET_HOSTILE_RANDOM_NOT_TOP')
			when target_type = 7 then concat(target_type, ' SMART_TARGET_ACTION_INVOKER')
			when target_type = 8 then concat(target_type, ' SMART_TARGET_POSITION')
			when target_type = 9 then concat(target_type, ' SMART_TARGET_CREATURE_RANGE')
			when target_type = 10 then concat(target_type, ' SMART_TARGET_CREATURE_GUID')
			when target_type = 11 then concat(target_type, ' SMART_TARGET_CREATURE_DISTANCE')
			when target_type = 12 then concat(target_type, ' SMART_TARGET_STORED')
			when target_type = 13 then concat(target_type, ' SMART_TARGET_GAMEOBJECT_RANGE')
			when target_type = 14 then concat(target_type, ' SMART_TARGET_GAMEOBJECT_GUID')
			when target_type = 15 then concat(target_type, ' SMART_TARGET_GAMEOBJECT_DISTANCE')
			when target_type = 16 then concat(target_type, ' SMART_TARGET_INVOKER_PARTY')
			when target_type = 17 then concat(target_type, ' SMART_TARGET_PLAYER_RANGE')
			when target_type = 18 then concat(target_type, ' SMART_TARGET_PLAYER_DISTANCE')
			when target_type = 19 then concat(target_type, ' SMART_TARGET_CLOSEST_CREATURE')
			when target_type = 20 then concat(target_type, ' SMART_TARGET_CLOSEST_GAMEOBJECT')
			when target_type = 21 then concat(target_type, ' SMART_TARGET_CLOSEST_PLAYER')
			when target_type = 22 then concat(target_type, ' SMART_TARGET_ACTION_INVOKER_VEHICLE')
			when target_type = 23 then concat(target_type, ' SMART_TARGET_OWNER_OR_SUMMONER')
			when target_type = 24 then concat(target_type, ' SMART_TARGET_THREAT_LIST')
			when target_type = 25 then concat(target_type, ' SMART_TARGET_CLOSEST_ENEMY')
			when target_type = 26 then concat(target_type, ' SMART_TARGET_CLOSEST_FRIENDLY')
			when target_type = 27 then concat(target_type, ' SMART_TARGET_LOOT_RECIPIENTS')
			when target_type = 28 then concat(target_type, ' SMART_TARGET_FARTHEST')
			when target_type = 29 then concat(target_type, ' SMART_TARGET_VEHICLE_ACCESSORY')
			when target_type = 30 then concat(target_type, ' SMART_TARGET_CLOSEST_UNSPAWNED_GAMEOBJECT')
		end as Target_Type,
		target_param1,
		target_param2,
		target_param3,
		comment
	from smart_scripts where entryorguid = entryInput
	union
	select @name
		, id
		, case when source_type = 0 then Concat(source_type,' Creature')
			when source_type = 1 then concat(source_type,' Game Object')
			when source_type = 9 then Concat(source_type, ' Action',right(entryorguid,2))
		end as Source_Type,
		link,
		event_phase_mask,
		event_chance,
		event_flags,
		case when event_type = 0 then concat(event_type, ' SMART_EVENT_UPDATE_IC')
			when event_type = 1 then concat(event_type, ' SMART_EVENT_UPDATE_OOC')
			when event_type = 2 then concat(event_type, ' SMART_EVENT_HEALTH_PCT')
			when event_type = 3 then concat(event_type, ' SMART_EVENT_MANA_PCT')
			when event_type = 4 then concat(event_type, ' SMART_EVENT_AGGRO')
			when event_type = 5 then concat(event_type, ' SMART_EVENT_KILL')
			when event_type = 6 then concat(event_type, ' SMART_EVENT_DEATH')
			when event_type = 7 then concat(event_type, ' SMART_EVENT_EVADE')
			when event_type = 8 then concat(event_type, ' SMART_EVENT_SPELLHIT')
			when event_type = 9 then concat(event_type, ' SMART_EVENT_RANGE')
			when event_type = 10 then concat(event_type, ' SMART_EVENT_OOC_LOS')
			when event_type = 11 then concat(event_type, ' SMART_EVENT_RESPAWN')
			when event_type = 12 then concat(event_type, ' SMART_EVENT_TARGET_HEALTH_PCT')
			when event_type = 13 then concat(event_type, ' SMART_EVENT_VICTIM_CASTING')
			when event_type = 14 then concat(event_type, ' SMART_EVENT_FRIENDLY_HEALTH')
			when event_type = 15 then concat(event_type, ' SMART_EVENT_FRIENDLY_IS_CC')
			when event_type = 16 then concat(event_type, ' SMART_EVENT_FRIENDLY_MISSING_BUFF')
			when event_type = 17 then concat(event_type, ' SMART_EVENT_SUMMONED_UNIT')
			when event_type = 18 then concat(event_type, ' SMART_EVENT_TARGET_MANA_PCT')
			when event_type = 19 then concat(event_type, ' SMART_EVENT_ACCEPTED_QUEST')
			when event_type = 20 then concat(event_type, ' SMART_EVENT_REWARD_QUEST')
			when event_type = 21 then concat(event_type, ' SMART_EVENT_REACHED_HOME')
			when event_type = 22 then concat(event_type, ' SMART_EVENT_RECEIVE_EMOTE')
			when event_type = 23 then concat(event_type, ' SMART_EVENT_HAS_AURA')
			when event_type = 24 then concat(event_type, ' SMART_EVENT_TARGET_BUFFED')
			when event_type = 25 then concat(event_type, ' SMART_EVENT_RESET')
			when event_type = 26 then concat(event_type, ' SMART_EVENT_IC_LOS')
			when event_type = 27 then concat(event_type, ' SMART_EVENT_PASSENGER_BOARDED')
			when event_type = 28 then concat(event_type, ' SMART_EVENT_PASSENGER_REMOVED')
			when event_type = 29 then concat(event_type, ' SMART_EVENT_CHARMED')
			when event_type = 30 then concat(event_type, ' SMART_EVENT_CHARMED_TARGET')
			when event_type = 31 then concat(event_type, ' SMART_EVENT_SPELLHIT_TARGET')
			when event_type = 32 then concat(event_type, ' SMART_EVENT_DAMAGED')
			when event_type = 33 then concat(event_type, ' SMART_EVENT_DAMAGED_TARGET')
			when event_type = 34 then concat(event_type, ' SMART_EVENT_MOVEMENTINFORM')
			when event_type = 35 then concat(event_type, ' SMART_EVENT_SUMMON_DESPAWNED')
			when event_type = 36 then concat(event_type, ' SMART_EVENT_CORPSE_REMOVED')
			when event_type = 37 then concat(event_type, ' SMART_EVENT_AI_INIT')
			when event_type = 38 then concat(event_type, ' SMART_EVENT_DATA_SET')
			when event_type = 39 then concat(event_type, ' SMART_EVENT_WAYPOINT_START')
			when event_type = 40 then concat(event_type, ' SMART_EVENT_WAYPOINT_REACHED')
			when event_type = 41 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_ADDPLAYER')
			when event_type = 42 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_ADDCREATURE')
			when event_type = 43 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_REMOVE_PLAYER')
			when event_type = 44 then concat(event_type, ' X_SMART_EVENT_TRANSPORT_RELOCATE')
			when event_type = 45 then concat(event_type, ' X_SMART_EVENT_INSTANCE_PLAYER_ENTER')
			when event_type = 46 then concat(event_type, ' SMART_EVENT_AREATRIGGER_ONTRIGGER')
			when event_type = 47 then concat(event_type, ' X_SMART_EVENT_QUEST_ACCEPTED')
			when event_type = 48 then concat(event_type, ' X_SMART_EVENT_QUEST_OBJ_COMPLETION')
			when event_type = 49 then concat(event_type, ' X_SMART_EVENT_QUEST_COMPLETION')
			when event_type = 50 then concat(event_type, ' X_SMART_EVENT_QUEST_REWARDED')
			when event_type = 51 then concat(event_type, ' X_SMART_EVENT_QUEST_FAIL')
			when event_type = 52 then concat(event_type, ' SMART_EVENT_TEXT_OVER')
			when event_type = 53 then concat(event_type, ' SMART_EVENT_RECEIVE_HEAL')
			when event_type = 54 then concat(event_type, ' SMART_EVENT_JUST_SUMMONED')
			when event_type = 55 then concat(event_type, ' SMART_EVENT_WAYPOINT_PAUSED')
			when event_type = 56 then concat(event_type, ' SMART_EVENT_WAYPOINT_RESUMED')
			when event_type = 57 then concat(event_type, ' SMART_EVENT_WAYPOINT_STOPPED')
			when event_type = 58 then concat(event_type, ' SMART_EVENT_WAYPOINT_ENDED')
			when event_type = 59 then concat(event_type, ' SMART_EVENT_TIMED_EVENT_TRIGGERED')
			when event_type = 60 then concat(event_type, ' SMART_EVENT_UPDATE')
			when event_type = 61 then concat(event_type, ' SMART_EVENT_LINK')
			when event_type = 62 then concat(event_type, ' SMART_EVENT_GOSSIP_SELECT')
			when event_type = 63 then concat(event_type, ' SMART_EVENT_JUST_CREATED')
			when event_type = 64 then concat(event_type, ' SMART_EVENT_GOSSIP_HELLO')
			when event_type = 65 then concat(event_type, ' SMART_EVENT_FOLLOW_COMPLETED')
			when event_type = 66 then concat(event_type, ' SMART_EVENT_EVENT_PHASE_CHANGE')
			when event_type = 67 then concat(event_type, ' SMART_EVENT_IS_BEHIND_TARGET')
			when event_type = 68 then concat(event_type, ' SMART_EVENT_GAME_EVENT_START')
			when event_type = 69 then concat(event_type, ' SMART_EVENT_GAME_EVENT_END')
			when event_type = 70 then concat(event_type, ' SMART_EVENT_GO_LOOT_STATE_CHANGED')
			when event_type = 71 then concat(event_type, ' SMART_EVENT_GO_EVENT_INFORM')
			when event_type = 72 then concat(event_type, ' SMART_EVENT_ACTION_DONE')
			when event_type = 73 then concat(event_type, ' SMART_EVENT_ON_SPELLCLICK')
			when event_type = 74 then concat(event_type, ' SMART_EVENT_FRIENDLY_HEALTH_PCT')
			when event_type = 75 then concat(event_type, ' SMART_EVENT_DISTANCE_CREATURE')
			when event_type = 76 then concat(event_type, ' SMART_EVENT_DISTANCE_GAMEOBJECT')
			when event_type = 77 then concat(event_type, ' SMART_EVENT_COUNTER_SET')
			when event_type = 78 then concat(event_type, ' SMART_EVENT_SCENE_START')
			when event_type = 79 then concat(event_type, ' SMART_EVENT_SCENE_TRIGGER')
			when event_type = 80 then concat(event_type, ' SMART_EVENT_SCENE_CANCEL')
			when event_type = 81 then concat(event_type, ' SMART_EVENT_SCENE_COMPLETE')
			when event_type = 82 then concat(event_type, ' SMART_EVENT_SUMMONED_UNIT_DIES')
		end as Event_Type,
		event_param1,
		event_param2,
		event_param3,
		event_param4,
		event_param5,
		case when action_type = 0 then concat(action_type, ' SMART_ACTION_NONE')
			when action_type = 1 then concat(action_type, ' SMART_ACTION_TALK')
			when action_type = 2 then concat(action_type, ' SMART_ACTION_SET_FACTION')
			when action_type = 3 then concat(action_type, ' SMART_ACTION_MORPH_TO_ENTRY_OR_MODEL')
			when action_type = 4 then concat(action_type, ' SMART_ACTION_SOUND')
			when action_type = 5 then concat(action_type, ' SMART_ACTION_PLAY_EMOTE')
			when action_type = 6 then concat(action_type, ' SMART_ACTION_FAIL_QUEST')
			when action_type = 7 then concat(action_type, ' SMART_ACTION_OFFER_QUEST')
			when action_type = 8 then concat(action_type, ' SMART_ACTION_SET_REACT_STATE')
			when action_type = 9 then concat(action_type, ' SMART_ACTION_ACTIVATE_GOBJECT')
			when action_type = 10 then concat(action_type, ' SMART_ACTION_RANDOM_EMOTE')
			when action_type = 11 then concat(action_type, ' SMART_ACTION_CAST')
			when action_type = 12 then concat(action_type, ' SMART_ACTION_SUMMON_CREATURE')
			when action_type = 13 then concat(action_type, ' SMART_ACTION_THREAT_SINGLE_PCT')
			when action_type = 14 then concat(action_type, ' SMART_ACTION_THREAT_ALL_PCT')
			when action_type = 15 then concat(action_type, ' SMART_ACTION_CALL_AREAEXPLOREDOREVENTHAPPENS')
			when action_type = 16 then concat(action_type, ' SMART_ACTION_SET_INGAME_PHASE_ID')
			when action_type = 17 then concat(action_type, ' SMART_ACTION_SET_EMOTE_STATE')
			when action_type = 18 then concat(action_type, ' SMART_ACTION_SET_UNIT_FLAG')
			when action_type = 19 then concat(action_type, ' SMART_ACTION_REMOVE_UNIT_FLAG')
			when action_type = 20 then concat(action_type, ' SMART_ACTION_AUTO_ATTACK')
			when action_type = 21 then concat(action_type, ' SMART_ACTION_ALLOW_COMBAT_MOVEMENT')
			when action_type = 22 then concat(action_type, ' SMART_ACTION_SET_EVENT_PHASE')
			when action_type = 23 then concat(action_type, ' SMART_ACTION_INC_EVENT_PHASE')
			when action_type = 24 then concat(action_type, ' SMART_ACTION_EVADE')
			when action_type = 25 then concat(action_type, ' SMART_ACTION_FLEE_FOR_ASSIST')
			when action_type = 26 then concat(action_type, ' SMART_ACTION_CALL_GROUPEVENTHAPPENS')
			when action_type = 27 then concat(action_type, ' SMART_ACTION_COMBAT_STOP')
			when action_type = 28 then concat(action_type, ' SMART_ACTION_REMOVEAURASFROMSPELL')
			when action_type = 29 then concat(action_type, ' SMART_ACTION_FOLLOW')
			when action_type = 30 then concat(action_type, ' SMART_ACTION_RANDOM_PHASE')
			when action_type = 31 then concat(action_type, ' SMART_ACTION_RANDOM_PHASE_RANGE')
			when action_type = 32 then concat(action_type, ' SMART_ACTION_RESET_GOBJECT')
			when action_type = 33 then concat(action_type, ' SMART_ACTION_CALL_KILLEDMONSTER')
			when action_type = 34 then concat(action_type, ' SMART_ACTION_SET_INST_DATA')
			when action_type = 35 then concat(action_type, ' SMART_ACTION_SET_INST_DATA64')
			when action_type = 36 then concat(action_type, ' SMART_ACTION_UPDATE_TEMPLATE')
			when action_type = 37 then concat(action_type, ' SMART_ACTION_DIE')
			when action_type = 38 then concat(action_type, ' SMART_ACTION_SET_IN_COMBAT_WITH_ZONE')
			when action_type = 39 then concat(action_type, ' SMART_ACTION_CALL_FOR_HELP')
			when action_type = 40 then concat(action_type, ' SMART_ACTION_SET_SHEATH')
			when action_type = 41 then concat(action_type, ' SMART_ACTION_FORCE_DESPAWN')
			when action_type = 42 then concat(action_type, ' SMART_ACTION_SET_INVINCIBILITY_HP_LEVEL')
			when action_type = 43 then concat(action_type, ' SMART_ACTION_MOUNT_TO_ENTRY_OR_MODEL')
			when action_type = 44 then concat(action_type, ' SMART_ACTION_SET_INGAME_PHASE_GROUP (for 4.3.4 +)')
			when action_type = 45 then concat(action_type, ' SMART_ACTION_SET_DATA')
			when action_type = 46 then concat(action_type, ' SMART_ACTION_ATTACK_STOP')
			when action_type = 47 then concat(action_type, ' SMART_ACTION_SET_VISIBILITY')
			when action_type = 48 then concat(action_type, ' SMART_ACTION_SET_ACTIVE')
			when action_type = 49 then concat(action_type, ' SMART_ACTION_ATTACK_START')
			when action_type = 50 then concat(action_type, ' SMART_ACTION_SUMMON_GO')
			when action_type = 51 then concat(action_type, ' SMART_ACTION_KILL_UNIT')
			when action_type = 52 then concat(action_type, ' SMART_ACTION_ACTIVATE_TAXI')
			when action_type = 53 then concat(action_type, ' SMART_ACTION_WP_START')
			when action_type = 54 then concat(action_type, ' SMART_ACTION_WP_PAUSE')
			when action_type = 55 then concat(action_type, ' SMART_ACTION_WP_STOP')
			when action_type = 56 then concat(action_type, ' SMART_ACTION_ADD_ITEM')
			when action_type = 57 then concat(action_type, ' SMART_ACTION_REMOVE_ITEM')
			when action_type = 58 then concat(action_type, ' SMART_ACTION_INSTALL_AI_TEMPLATE')
			when action_type = 59 then concat(action_type, ' SMART_ACTION_SET_RUN')
			when action_type = 60 then concat(action_type, ' SMART_ACTION_SET_DISABLE_GRAVITY')
			when action_type = 61 then concat(action_type, ' SMART_ACTION_SET_SWIM')
			when action_type = 62 then concat(action_type, ' SMART_ACTION_TELEPORT')
			when action_type = 63 then concat(action_type, ' SMART_ACTION_SET_COUNTER')
			when action_type = 64 then concat(action_type, ' SMART_ACTION_STORE_TARGET_LIST')
			when action_type = 65 then concat(action_type, ' SMART_ACTION_WP_RESUME')
			when action_type = 66 then concat(action_type, ' SMART_ACTION_SET_ORIENTATION')
			when action_type = 67 then concat(action_type, ' SMART_ACTION_CREATE_TIMED_EVENT')
			when action_type = 68 then concat(action_type, ' SMART_ACTION_PLAYMOVIE')
			when action_type = 69 then concat(action_type, ' SMART_ACTION_MOVE_TO_POS')
			when action_type = 70 then concat(action_type, ' SMART_ACTION_ENABLE_TEMP_GOBJ')
			when action_type = 71 then concat(action_type, ' SMART_ACTION_EQUIP')
			when action_type = 72 then concat(action_type, ' SMART_ACTION_CLOSE_GOSSIP')
			when action_type = 73 then concat(action_type, ' SMART_ACTION_TRIGGER_TIMED_EVENT')
			when action_type = 74 then concat(action_type, ' SMART_ACTION_REMOVE_TIMED_EVENT')
			when action_type = 75 then concat(action_type, ' SMART_ACTION_ADD_AURA')
			when action_type = 76 then concat(action_type, ' SMART_ACTION_OVERRIDE_SCRIPT_BASE_OBJECT')
			when action_type = 77 then concat(action_type, ' SMART_ACTION_RESET_SCRIPT_BASE_OBJECT')
			when action_type = 78 then concat(action_type, ' SMART_ACTION_CALL_SCRIPT_RESET')
			when action_type = 79 then concat(action_type, ' SMART_ACTION_SET_RANGED_MOVEMENT')
			when action_type = 80 then concat(action_type, ' SMART_ACTION_CALL_TIMED_ACTIONLIST')
			when action_type = 81 then concat(action_type, ' SMART_ACTION_SET_NPC_FLAG')
			when action_type = 82 then concat(action_type, ' SMART_ACTION_ADD_NPC_FLAG')
			when action_type = 83 then concat(action_type, ' SMART_ACTION_REMOVE_NPC_FLAG')
			when action_type = 84 then concat(action_type, ' SMART_ACTION_SIMPLE_TALK')
			when action_type = 85 then concat(action_type, ' SMART_ACTION_SELF_CAST')
			when action_type = 86 then concat(action_type, ' SMART_ACTION_CROSS_CAST')
			when action_type = 87 then concat(action_type, ' SMART_ACTION_CALL_RANDOM_TIMED_ACTIONLIST')
			when action_type = 88 then concat(action_type, ' SMART_ACTION_CALL_RANDOM_RANGE_TIMED_ACTIONLIST')
			when action_type = 89 then concat(action_type, ' SMART_ACTION_RANDOM_MOVE')
			when action_type = 90 then concat(action_type, ' SMART_ACTION_SET_UNIT_FIELD_BYTES_1')
			when action_type = 91 then concat(action_type, ' SMART_ACTION_REMOVE_UNIT_FIELD_BYTES_1')
			when action_type = 92 then concat(action_type, ' SMART_ACTION_INTERRUPT_SPELL')
			when action_type = 93 then concat(action_type, ' SMART_ACTION_SEND_GO_CUSTOM_ANIM')
			when action_type = 94 then concat(action_type, ' SMART_ACTION_SET_DYNAMIC_FLAG')
			when action_type = 95 then concat(action_type, ' SMART_ACTION_ADD_DYNAMIC_FLAG')
			when action_type = 96 then concat(action_type, ' SMART_ACTION_REMOVE_DYNAMIC_FLAG')
			when action_type = 97 then concat(action_type, ' SMART_ACTION_JUMP_TO_POS')
			when action_type = 98 then concat(action_type, ' SMART_ACTION_SEND_GOSSIP_MENU')
			when action_type = 99 then concat(action_type, ' SMART_ACTION_GO_SET_LOOT_STATE')
			when action_type = 100 then concat(action_type, ' SMART_ACTION_SEND_TARGET_TO_TARGET')
			when action_type = 101 then concat(action_type, ' SMART_ACTION_SET_HOME_POS')
			when action_type = 102 then concat(action_type, ' SMART_ACTION_SET_HEALTH_REGEN')
			when action_type = 103 then concat(action_type, ' SMART_ACTION_SET_ROOT')
			when action_type = 104 then concat(action_type, ' SMART_ACTION_SET_GO_FLAG')
			when action_type = 105 then concat(action_type, ' SMART_ACTION_ADD_GO_FLAG')
			when action_type = 106 then concat(action_type, ' SMART_ACTION_REMOVE_GO_FLAG')
			when action_type = 107 then concat(action_type, ' SMART_ACTION_SUMMON_CREATURE_GROUP')
			when action_type = 108 then concat(action_type, ' SMART_ACTION_SET_POWER')
			when action_type = 109 then concat(action_type, ' SMART_ACTION_ADD_POWER')
			when action_type = 110 then concat(action_type, ' SMART_ACTION_REMOVE_POWER')
			when action_type = 111 then concat(action_type, ' SMART_ACTION_GAME_EVENT_STOP')
			when action_type = 112 then concat(action_type, ' SMART_ACTION_GAME_EVENT_START')
			when action_type = 113 then concat(action_type, ' SMART_ACTION_START_CLOSEST_WAYPOINT')
			when action_type = 114 then concat(action_type, ' SMART_ACTION_MOVE_OFFSET')
			when action_type = 115 then concat(action_type, ' SMART_ACTION_RANDOM_SOUND')
			when action_type = 116 then concat(action_type, ' SMART_ACTION_SET_CORPSE_DELAY')
			when action_type = 117 then concat(action_type, ' SMART_ACTION_DISABLE_EVADE')
			when action_type = 118 then concat(action_type, ' SMART_ACTION_GO_SET_GO_STATE')
			when action_type = 119 then concat(action_type, ' SMART_ACTION_SET_CAN_FLY')
			when action_type = 120 then concat(action_type, ' SMART_ACTION_REMOVE_AURAS_BY_TYPE')
			when action_type = 121 then concat(action_type, ' SMART_ACTION_SET_SIGHT_DIST')
			when action_type = 122 then concat(action_type, ' SMART_ACTION_FLEE')
			when action_type = 123 then concat(action_type, ' SMART_ACTION_ADD_THREAT')
			when action_type = 124 then concat(action_type, ' SMART_ACTION_LOAD_EQUIPMENT')
			when action_type = 125 then concat(action_type, ' SMART_ACTION_TRIGGER_RANDOM_TIMED_EVENT')
			when action_type = 126 then concat(action_type, ' SMART_ACTION_REMOVE_ALL_GAMEOBJECTS')
			when action_type = 127 then concat(action_type, ' SMART_ACTION_PAUSE_MOVEMENT')
			when action_type = 128 then concat(action_type, ' SMART_ACTION_PLAY_ANIMKIT')
			when action_type = 129 then concat(action_type, ' SMART_ACTION_SCENE_PLAY')
			when action_type = 130 then concat(action_type, ' SMART_ACTION_SCENE_CANCEL')
			when action_type = 131 then concat(action_type, ' SMART_ACTION_SPAWN_SPAWNGROUP')
			when action_type = 132 then concat(action_type, ' SMART_ACTION_DESPAWN_SPAWNGROUP')
			when action_type = 133 then concat(action_type, ' SMART_ACTION_RESPAWN_BY_SPAWNID')
			when action_type = 134 then concat(action_type, ' SMART_ACTION_INVOKER_CAST')
			when action_type = 135 then concat(action_type, ' SMART_ACTION_PLAY_CINEMATIC ')
			when action_type = 136 then concat(action_type, ' SMART_ACTION_SET_MOVEMENT_SPEED ')
			when action_type = 137 then concat(action_type, ' SMART_ACTION_PLAY_SPELL_VISUAL_KIT')
			when action_type = 138 then concat(action_type, ' SMART_ACTION_OVERRIDE_LIGHT')
			when action_type = 139 then concat(action_type, ' SMART_ACTION_OVERRIDE_WEATHER')
		end as Action_Type,
		action_param1,
		action_param2,
		action_param3,
		action_param4,
		action_param5,
		action_param6,
		case when target_type = 0 then concat(target_type, ' SMART_TARGET_NONE')
			when target_type = 1 then concat(target_type, ' SMART_TARGET_SELF')
			when target_type = 2 then concat(target_type, ' SMART_TARGET_VICTIM')
			when target_type = 3 then concat(target_type, ' SMART_TARGET_HOSTILE_SECOND_AGGRO')
			when target_type = 4 then concat(target_type, ' SMART_TARGET_HOSTILE_LAST_AGGRO')
			when target_type = 5 then concat(target_type, ' SMART_TARGET_HOSTILE_RANDOM')
			when target_type = 6 then concat(target_type, ' SMART_TARGET_HOSTILE_RANDOM_NOT_TOP')
			when target_type = 7 then concat(target_type, ' SMART_TARGET_ACTION_INVOKER')
			when target_type = 8 then concat(target_type, ' SMART_TARGET_POSITION')
			when target_type = 9 then concat(target_type, ' SMART_TARGET_CREATURE_RANGE')
			when target_type = 10 then concat(target_type, ' SMART_TARGET_CREATURE_GUID')
			when target_type = 11 then concat(target_type, ' SMART_TARGET_CREATURE_DISTANCE')
			when target_type = 12 then concat(target_type, ' SMART_TARGET_STORED')
			when target_type = 13 then concat(target_type, ' SMART_TARGET_GAMEOBJECT_RANGE')
			when target_type = 14 then concat(target_type, ' SMART_TARGET_GAMEOBJECT_GUID')
			when target_type = 15 then concat(target_type, ' SMART_TARGET_GAMEOBJECT_DISTANCE')
			when target_type = 16 then concat(target_type, ' SMART_TARGET_INVOKER_PARTY')
			when target_type = 17 then concat(target_type, ' SMART_TARGET_PLAYER_RANGE')
			when target_type = 18 then concat(target_type, ' SMART_TARGET_PLAYER_DISTANCE')
			when target_type = 19 then concat(target_type, ' SMART_TARGET_CLOSEST_CREATURE')
			when target_type = 20 then concat(target_type, ' SMART_TARGET_CLOSEST_GAMEOBJECT')
			when target_type = 21 then concat(target_type, ' SMART_TARGET_CLOSEST_PLAYER')
			when target_type = 22 then concat(target_type, ' SMART_TARGET_ACTION_INVOKER_VEHICLE')
			when target_type = 23 then concat(target_type, ' SMART_TARGET_OWNER_OR_SUMMONER')
			when target_type = 24 then concat(target_type, ' SMART_TARGET_THREAT_LIST')
			when target_type = 25 then concat(target_type, ' SMART_TARGET_CLOSEST_ENEMY')
			when target_type = 26 then concat(target_type, ' SMART_TARGET_CLOSEST_FRIENDLY')
			when target_type = 27 then concat(target_type, ' SMART_TARGET_LOOT_RECIPIENTS')
			when target_type = 28 then concat(target_type, ' SMART_TARGET_FARTHEST')
			when target_type = 29 then concat(target_type, ' SMART_TARGET_VEHICLE_ACCESSORY')
			when target_type = 30 then concat(target_type, ' SMART_TARGET_CLOSEST_UNSPAWNED_GAMEOBJECT')
		end as Target_Type,
		target_param1,
		target_param2,
		target_param3,
		comment
	from smart_scripts where entryorguid like Concat(entryInput, '__') and length(entryorguid) = @inputActionLength
	order by source_type, id;
END //